### ISSUE TITLE
When is the "Automatic TensorFlow to deeplearn.js" feature expected to become available?

### ISSUE THREAD

**Issue by kaihuchen** [PAIR-code/deeplearnjs#17]
I managed to get deeplearnjs installed on my server, and I am trying to extend the examples page (i.e., the page https://pair-code.github.io/deeplearnjs/demos/model-builder/model-builder-demo.html , but on my server) by adding an Inception V3 model there (since I am feeling ambitious) beyond the current MNIST and CIFAR-10 models.

If I understand correctly, then per instructions on [deeplearnjs' Port TensorFlow Model page](https://pair-code.github.io/deeplearnjs/demos/mnist/mnist.html), currently I will need to recreate the entire model manually in deeplearnjs, which is a lot of work. I found it mentioned in the Roadmap where a GraphDef utility will do this automatically, and I would like to cast my vote for this to become available sooner rather than later. Without this feature it would be hard to work on more complex models. Thanks!

**Comment by nsthorat** [comment]
So, just so you know, I have tried porting inception V3. We currently have a problem with max texture size limits because one of the activations would exceed the maximum width on some computers (16k on my mac). We're working on "logical sampling" which allows us to pack memory in WebGLTextures so that we don't exceed the maximum dimensions of a texture allowed by the browser. We're working on it.

As for dumping a GraphDef, there are a couple issues we need to get resolved first. Our convolution2d's don't have exactly the same padding API as TensorFlow, but this is going to be fixed when we do the logical sampling work. This is super high priority for us, hopefully this happens within a month or two (I'm sorry).

Lastly, we also have ported SqueezeNet which is only ~5MB parameters, which gets AlexNet-level accuracy, whereas Inception V3 is 200MB. We're using SqueezeNet in the webcam ImageNet demo on the homepage, and we're going to use it for new demos for transfer learning tasks. I put SqueezeNet into a "models" directory for inference that lets you grab whatever activation you want from the inference pass, you can check it out here: https://github.com/PAIR-code/deeplearnjs/blob/master/demos/models/squeezenet.ts. Here is the demo: https://pair-code.github.io/deeplearnjs/demos/imagenet/imagenet-demo.html

Hope this helps, sorry I don't have a simple answer :)

**Comment by kaihuchen** [comment]
@nsthorat  This is super helpful, and I want you to know that your great work here is very much appreciated!

I did not realize that the ImageNet demo is using SqueezeNet, and I will certainly be happy to try it out first.

**Comment by nsthorat** [comment]
Awesome. I'm really happy this tool is helpful to the community, I'm really interested to see what you build!

**Comment by galsasson** [comment]
Hi @nsthorat, nice to see this effort and thanks.
Just checking to see if there's any progress on this. I would like to add a custom VAE model into the framework, what is the best way right now?

**Comment by nsthorat** [comment]
Hi, just looping back on this since we've announced TensorFlow.js and automatic model porting tools. Check out the tutorials here: http://js.tensorflow.org/tutorials

For TensorFlow SavedModels, use this repo: https://github.com/tensorflow/tfjs-converter
