### ISSUE TITLE
Create our own documentation generator.

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#242]
We currently use typedoc to do documentation generation for this page:
https://deeplearnjs.org/docs/api/globals.html

However, typedoc doesn't do what we want it to do, and this page isn't customizable.

What we really want is a way to build documentation by starting from [index.ts](https://github.com/PAIR-code/deeplearnjs/blob/master/src/index.ts) which defines our public API, and only expose functionality from this file.

TypeScript compiler should give you enough information to build this page, and once we dump a JSON-ified version of this, we can build a very simple webpage that renders it.

**Comment by ManrajGrover** [comment]
@nsthorat I've been looking into this issue for sometime now and here are my findings:

1. Specifying a root entry point for TypeDoc is a hassle and looks like TypeDoc does not support what we want. See (https://github.com/TypeStrong/typedoc/issues/172, https://github.com/TypeStrong/typedoc/issues/388)
2. We might need to specify files that we want to expose separately in `tsconfig-doc.json` and hide private functions/interfaces/class using`@hidden`.
3. We can then use either the default theme by typedoc or any other good starting point and build upon the design we want.

I would need your inputs on the same and move forward in building documentation generator.

Some references I found:
1. [Create beautiful documentation](https://blog.ironcorelabs.com/create-beautiful-documentation-7c66a2c5fa19)
2. [Generating documentation for TypeScript projects](https://blog.cloudflare.com/generating-documentation-for-typescript-projects)

**Comment by dsmilkov** [comment]
Hi @ManrajGrover,

The research you did is a great start and also explains our motivation to build our own generator, instead of typedoc. Some comments inline.

> Specifying a root entry point for TypeDoc is a hassle and looks like TypeDoc does not support what we want. See (TypeStrong/typedoc#172, TypeStrong/typedoc#388)

Yup, we also ran across this limitation, thus motivating us to think about building our own generator.

> We might need to specify files that we want to expose separately in tsconfig-doc.json and hide private functions/interfaces/class using@hidden.

Yup, this is what we are doing now. See [this](https://github.com/PAIR-code/deeplearnjs/blob/a467449812161345e95aff1c191c0d806a82d355/src/data/input_provider.ts#L43) example in the codebase, but it's a fragile process and hard to keep in sync (e.g. we need to keep `tsconfig-doc.json` up to date when adding new files to the codebase)

> We can then use either the default theme by typedoc or any other good starting point and build upon the design we want.

I think using the typedoc theme generator is a good idea, and we can make sure that our own generator produces a json that typedoc html generator understands.

**Comment by dsmilkov** [comment]
[This page](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker) might be a good starting point for a custom doc generator.

**Comment by ManrajGrover** [comment]
@dsmilkov Keeping things updated here, I've opened an issue on [TypeDoc](https://github.com/TypeStrong/typedoc/issues/639) regarding this. Also, I've explored the given code and tried tweaking it for our use case but found documentation needs a lot of upgrading (See [issue](https://github.com/Microsoft/TypeScript/issues/17147)). One might need to go through examples/starter codes to understand the API better.

**Comment by dsmilkov** [comment]
Thanks for filing those issue! That sounds like a good start.

**Comment by nsthorat** [comment]
This is fixed. See you tomorrow :D
