### ISSUE TITLE
Any Phonegap Developers using deeplearnjs?

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#272]
Before deeplearnjs reaches version 1.0 can someone look into getting it to work on Phonegap or PhoengapBuild (The online version is at https://build.phonegap.com  ). Phonegap takes an index.html file from almost any website that works on Chrome and converts it into an Android, Windows and / or iOS mobile App. Very slick.

Presently the compiler refuses to accept the deeplearnjs script. Not sure why. I will look into it more just wondering if anyone out their using deeplearnjs has also used phonegap?

**Comment by todrules** [comment]
What do you mean by "refuses to accept"? Also, how are you loading the script? And, what JS frameworks and module bundler are you using?

FYI - I can get it work with Cordova using Angular and Ionic w/ TypeScript. I just do an "npm install --save deeplearn", and then import the appropriate deeplearn components as needed in my project, for example - import { NdArray1D } from 'deeplearn'. Your mileage may vary depending on what type of module loader you're using, and if you're using TypeScript/E6.

**Comment by hpssjellis** [comment]
@todrules That is really positive that you can get it working with Cordova. I just re-tired on phonegapbuild and it did compile the package ready for download but when I installed in on my Android phone I got:


"App not installed.
The package appears to be corrupt."

I have not used the Phonegap or Cordova client for a few years so I will mess around with that and see what I can do. 

I am working from a static javascript website on my github at [https://github.com/hpssjellis/deeplearnjs-javascript-examples](https://github.com/hpssjellis/deeplearnjs-javascript-examples) and uploading it to  [https://build.phonegap.com](https://build.phonegap.com) that should reproduce my errors.

Knowing you can get it working with Cordova is great. Thanks for replying.

**Comment by todrules** [comment]
You might want to look at the Hello World example on the PhoneGap site here - http://docs.phonegap.com/tutorials/develop/hello-world-explained/. One thing that I didn't see in your repo is a link to the cordova.js file, which should look like this:

`<script type="text/javascript" src="cordova.js"></script>`

You won't have that file. PhoneGap should add the correct one when building your app. That walkthrough explains some other details on how to structure your app, too. My suggestion would be to create a vanilla HelloWorld PhoneGap app and get that running, then add the Deeplearn stuff to that. Usually, these builds expect a very specific configuration, including the config.xml details, in order to build correctly. 

Finally, one other thing that I usually run into - If you get the app to compile and install correctly, and you think it should be running, it could be some type of permission issue. You probably won't run into that on a HelloWorld-type app, but once you start adding plugins and accessing the native APIs, the permissions need to be added. Luckily, you can usually find examples of what you need online, though.

**Comment by hpssjellis** [comment]
I think you are correct with the permissions

.` <script src="https://unpkg.com/deeplearn"></script>`

is probably a permission error. 

Note: With [phonegap build](https://build.phonegap.com/) the cordova.js file is included automatically. Great to know that deeplearnjs works with cordova/phonegap, but I still want to see it working with phonegap build.

**Comment by hpssjellis** [comment]
Thanks @todrules 

I completely messed up my config.xml for the new build Cli 7.0.1 My setup wouldn't even get a helloworld index.html working. I am good now so closing the issue. Thanks for the help.
