### ISSUE TITLE
Can't build demos on 0.3.14

### ISSUE THREAD

**Issue by nkreeger** [PAIR-code/deeplearnjs#449]
getTexture() was dropped in NDArray and now some of the demos won't build:

https://github.com/PAIR-code/deeplearnjs/search?utf8=%E2%9C%93&q=getTexture&type=

@nsthorat @dsmilkov Not sure what is best practice to surface these textures through an NDArray is. Do you have any advice?

**Comment by dsmilkov** [comment]
I started working on a PR that upgrades the demos to use the new 0.3.14, where getTexture() is not present on NDArray. The solution will be to talk to the webgl backend directly and access the texture there.

Lesson we learned for the future: We would have avoided this breakage and allowed for soft transition if:
1) we released the post-global ndarray change with a new minor version `0.4.x`, as opposed to a new patch version `0.3.14`, since demos have a peer dependency on `~0.3.13` which resolves to `0.3.x` OR
2) changed our demos to have exact version on `0.3.13`

**Comment by dsmilkov** [comment]
[Here](https://reviewable.io/reviews/pair-code/deeplearnjs/455/demos/imagenet/imagenet.ts) is a code diff of an upcoming PR that shows how to access the texture for a given NDArray.

**Comment by dsmilkov** [comment]
Fixed by #461
