### ISSUE TITLE
How to save trained variables?

### ISSUE THREAD

**Issue by kimamula** [PAIR-code/deeplearnjs#483]
Is it possible to execute training with deeplearn.js and save the trained variables as JSON?

**Comment by kimamula** [comment]
Thank you for the response.

It seems your library serializes graphs, not trained variables.
I would like to save the training results of deeplearn.js just like TensorFlow does with checkpoint files.

**Comment by erikwilson** [comment]
I haven't used TensorFlow extensively so I'm not sure how how checkpoint differentiates graph operations from variable data or how that relates to your request. Deeplearn-graph-serializer supports the 'variable' operator for graphs, otherwise Scalars can be called with 'getValues' to retrieve raw values. Is there a specific DeepLearn class that you are trying to serialize?

**Comment by kimamula** [comment]
Ah, I see.
So if I have a variable tensor `v`, I can get its values by calling `v.node.data.getValues()`.
Thanks!

**Comment by nsthorat** [comment]
Just to follow up here, we're working on eager mode (getting rid of the graph / session and just using math). We'll provide a way to get the variables out!

**Comment by erikwilson** [comment]
Thanks for the update @nsthorat! Hopefully with that change we will still be able to save and restore the structure of an entire model, that seems like a useful feature.

**Comment by nsthorat** [comment]
Yes, that is a useful feature! The caveat is that models can be dynamic in eager mode, so serialization may have to include the .js file. Alternatively, we may add some "record" functionality to save / serialize a static model (meaning, no branching logic).

Expect some major updates from us in Q1 :)
