### ISSUE TITLE
Error in demo game_of_life

### ISSUE THREAD

**Issue by QuantumInformation** [PAIR-code/deeplearnjs#504]
Running `./scripts/watch-demo demos/game_of_life`

gives

➜  deeplearnjs git:(master) ✗  ./scripts/watch-demo demos/game_of_life
> Running in development mode
> Using external Poi config file
> location: "~/WebstormProjects/deeplearnjs/demos/poi.config.js"

TypeError: Cannot destructure property `useConfig` of 'undefined' or 'null'.
    at /Users/nikos/WebstormProjects/deeplearnjs/demos/node_modules/poi/lib/handle-options.js:97:1
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/nikos/WebstormProjects/deeplearnjs/demos/node_modules/co/index.js:65:19)
    at <anonymous>

 FAIL  Failed to start!

**Comment by nkreeger** [comment]
You might need to run the following:
$ cd demos/
$ yarn install
$ cd ../
$ ./scripts/watch-demo demos/game_of_life

I just ran a clean build and everything was fine on my machine.

**Comment by QuantumInformation** [comment]
I done npm install


Kind regards

Nikos
quantumjs.com

**Comment by dsmilkov** [comment]
Closing this issue. Feel free to reopen if other issues come out.

Regarding demos: There is a [working PR](https://github.com/pair-code/deeplearnjs/pull/505) that fixes all demos. There were small backwards incompatible changes in the library in order to align its API with TensorFlow (e.g. can't add/subtract/multiply/divide ndarrays of different dtypes, must cast)
