### ISSUE TITLE
math.multiply is listed in the API documentation but not yet relased

### ISSUE THREAD

**Issue by halatmit** [PAIR-code/deeplearnjs#56]

**Comment by mnottheone** [comment]
I am not sure what you mean by not released. I can see multiply operation implemented [here](https://github.com/PAIR-code/deeplearnjs/blob/master/src/ops/matmul.ts) and about usage I can see it being tested ( or used ) [here](https://github.com/PAIR-code/deeplearnjs/blob/c254d9510d4dae2b4f845a1536d1203d64066ec1/src/math/math_cpu_test.ts#L399) . If you are trying to use it, look for second link. 

Please comment below if there is still any doubt.

**Comment by halatmit** [comment]
According to Daniel, it's implemented but the new code hasn't been
published yet.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by dsmilkov** [comment]
To clarify, what @halatmit was confused by is that in the official API doc, we have `math.multiply`: https://pair-code.github.io/deeplearnjs/docs/api/classes/ndarraymathgpu.html#multiply

but in the javascript bundle we provide hosted at https://storage.googleapis.com/learnjs-data/deeplearn.js, that method doesn't exist.

This is because the javascript bundle corresponds to the 0.1.0 version, while the documentation was regenerated few days ago and points to the latest master version.

To avoid confusion like this in the future, we should have versioned doc links. For example https://pair-code.github.io/deeplearnjs/docs/api/0.1.0/... and https://pair-code.github.io/deeplearnjs/docs/api/latest/ for the latest version at master.

@nsthorat Curious about your thoughts.

**Comment by nsthorat** [comment]
I agree, we should have versioned doc links.

Here's what I think we should do:
1) Separate the doc building script from the website / demos building script. The two scripts will be "make-website" and "release-version".
2) "release-version" will now compile the bundle, and use the google cloud API to push a new version of the javascript library, release on npm, as well as build the API reference and update the github pages link.

This will probably require reworking some of the other scripts we have as well, but this seems like the right approach. WDYT?

**Comment by halatmit** [comment]
I haven't been involved in producing these, but this seem like a good
approach.


== Hal

Hal Abelson
hal@mit.edu
Prof. of Comp. Sci. and Eng.
MIT Dept. of Elec. Eng. and Comp. Sci.

**Comment by dsmilkov** [comment]
Closing this as we've been regenerating the website every time we release a new version so docs are in sync. Reopen if you run into more issues
