### ISSUE TITLE
Possible bug in Version 0.5.1 .print not working for Tensor Class

### ISSUE THREAD

**Issue by hpssjellis** [PAIR-code/deeplearnjs#822]
Possible bug in Version 0.5.1 dl.print not working for Tensor Class but works fine for the dl.tensor helper method

Run this code in a browser with the console open (ctrl-shift-I)
The alert just proves the Tensor was created.

```
<script src="https://unpkg.com/deeplearn@0.5.1/dist/deeplearn.js"> </script> 


<input type="button" value="Print works" onclick="{

   const myCheck  = dl.tensor([1, 2, 3, 4], [2, 2])
   alert(myCheck.indexToLoc(1))
   myCheck.print()
}"><br>


<input type="button" value="Does not work" onclick="{

   const myStuff  = new dl.Tensor([2,2],'float32',[1, 2, 3, 4]);
   alert(myStuff.indexToLoc(1))
   myStuff.print()
}"><br>
```

**Comment by dsmilkov** [comment]
Hi @hpssjellis ,

The constructor of Tensor is meant to be private (in typescript, the compiler won't let you use it). In our documentation for [`Tensor`](https://deeplearnjs.org/docs/api/index.html#class:dl.Tensor) we are referring the user to use `dl.tensor()` for tensor creation.

The reason print is not working is because the private Tensor constructor expects TypedArray as values, instead of regular array. We don't do this type of check in the c-tor since we assume the inputs have been sanitized.

**Comment by hpssjellis** [comment]
But when I extend the Tensor class, how to I construct it using dl.tensor  ?

See demo at [https://hpssjellis.github.io/deeplearnjs-javascript-examples/active-work/basic02.html](https://hpssjellis.github.io/deeplearnjs-javascript-examples/active-work/basic02.html)


Here is my class definition:

```
<script src="https://unpkg.com/deeplearn"> </script> 

<script>
        
class myTensor extends dl.Tensor {
    async myMethod()  {
       const myOutput =  await this.data()
       alert(myOutput)
    }  
}      
    
</script>

<input type="button" value="Extend Tensor Class" onclick="{   
   const myWeights  = new myTensor([2,2],'float32',[1,2,3,4]);
   myWeights.myMethod()
}"><br> 

```
