### ISSUE TITLE
util.js:79 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by cyilu** [PAIR-code/deeplearnjs#877]
My code is:
`let c=dl.tanh([0.2963064 , -0.4489866, 0.0725265 ,  0.1538655 , 0.363962  , -0.0452909,
          0.3438355 , -0.7197306, -0.0965203, 0.1176442 , 0.3955537 , -0.1697455,
          0.2924818 , -0.8240886, -0.107292 , -0.0213198, 0.5405946 , -0.0652936]);
 console.log(c);`

But console reports the error.

My first code is:
`let r_conv1 = dl.relu(conv2d(x_image, W_conv1) + b_conv1);`
,which reports the same error.

I need your help.Thanks.

**Comment by tafsiri** [comment]
Hi @cyilu You need to pass a tensor to `dl.tanh` instead of a regular array. See https://deeplearnjs.org/docs/api/index.html#dl.tanh for an example. 

You could either call `dl.tanh(dl.tensor[...])` or `dl.tensor([...]).tanh()`

In your second example you probably need to use an `add` operator rather than `+`

**Comment by cyilu** [comment]
Thank you.
